/*
 * This file is generated by jOOQ.
*/
package com.vzard.mycms.database.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAdmin extends Serializable {

    /**
     * Setter for <code>my-cms.admin.id</code>.
     */
    public IAdmin setId(Integer value);

    /**
     * Getter for <code>my-cms.admin.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>my-cms.admin.number</code>. 编号
     */
    public IAdmin setNumber(String value);

    /**
     * Getter for <code>my-cms.admin.number</code>. 编号
     */
    public String getNumber();

    /**
     * Setter for <code>my-cms.admin.name</code>. 姓名
     */
    public IAdmin setName(String value);

    /**
     * Getter for <code>my-cms.admin.name</code>. 姓名
     */
    public String getName();

    /**
     * Setter for <code>my-cms.admin.password</code>. 密码
     */
    public IAdmin setPassword(String value);

    /**
     * Getter for <code>my-cms.admin.password</code>. 密码
     */
    public String getPassword();

    /**
     * Setter for <code>my-cms.admin.created_at</code>. 创建时间
     */
    public IAdmin setCreatedAt(Timestamp value);

    /**
     * Getter for <code>my-cms.admin.created_at</code>. 创建时间
     */
    public Timestamp getCreatedAt();

    /**
     * Setter for <code>my-cms.admin.updated_at</code>. 更新时间
     */
    public IAdmin setUpdatedAt(Timestamp value);

    /**
     * Getter for <code>my-cms.admin.updated_at</code>. 更新时间
     */
    public Timestamp getUpdatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IAdmin
     */
    public void from(com.vzard.mycms.database.tables.interfaces.IAdmin from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IAdmin
     */
    public <E extends com.vzard.mycms.database.tables.interfaces.IAdmin> E into(E into);
}
