/*
 * This file is generated by jOOQ.
*/
package com.vzard.mycms.database.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITeacherCourse extends Serializable {

    /**
     * Setter for <code>my-cms.teacher_course.id</code>. id
     */
    public ITeacherCourse setId(Long value);

    /**
     * Getter for <code>my-cms.teacher_course.id</code>. id
     */
    public Long getId();

    /**
     * Setter for <code>my-cms.teacher_course.teacher_num</code>. 教师工号
     */
    public ITeacherCourse setTeacherNum(Long value);

    /**
     * Getter for <code>my-cms.teacher_course.teacher_num</code>. 教师工号
     */
    public Long getTeacherNum();

    /**
     * Setter for <code>my-cms.teacher_course.course_num</code>. 课程号
     */
    public ITeacherCourse setCourseNum(Long value);

    /**
     * Getter for <code>my-cms.teacher_course.course_num</code>. 课程号
     */
    public Long getCourseNum();

    /**
     * Setter for <code>my-cms.teacher_course.created_at</code>. 创建时间
     */
    public ITeacherCourse setCreatedAt(Timestamp value);

    /**
     * Getter for <code>my-cms.teacher_course.created_at</code>. 创建时间
     */
    public Timestamp getCreatedAt();

    /**
     * Setter for <code>my-cms.teacher_course.updated_at</code>. 更新时间
     */
    public ITeacherCourse setUpdatedAt(Timestamp value);

    /**
     * Getter for <code>my-cms.teacher_course.updated_at</code>. 更新时间
     */
    public Timestamp getUpdatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITeacherCourse
     */
    public void from(com.vzard.mycms.database.tables.interfaces.ITeacherCourse from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITeacherCourse
     */
    public <E extends com.vzard.mycms.database.tables.interfaces.ITeacherCourse> E into(E into);
}
