/*
 * This file is generated by jOOQ.
*/
package com.vzard.mycms.database.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITeacher extends Serializable {

    /**
     * Setter for <code>my-cms.teacher.number</code>. 工号
     */
    public ITeacher setNumber(Long value);

    /**
     * Getter for <code>my-cms.teacher.number</code>. 工号
     */
    public Long getNumber();

    /**
     * Setter for <code>my-cms.teacher.name</code>. 姓名
     */
    public ITeacher setName(String value);

    /**
     * Getter for <code>my-cms.teacher.name</code>. 姓名
     */
    public String getName();

    /**
     * Setter for <code>my-cms.teacher.password</code>. 密码
     */
    public ITeacher setPassword(String value);

    /**
     * Getter for <code>my-cms.teacher.password</code>. 密码
     */
    public String getPassword();

    /**
     * Setter for <code>my-cms.teacher.gender</code>. 性别
     */
    public ITeacher setGender(String value);

    /**
     * Getter for <code>my-cms.teacher.gender</code>. 性别
     */
    public String getGender();

    /**
     * Setter for <code>my-cms.teacher.office</code>. 办公室
     */
    public ITeacher setOffice(String value);

    /**
     * Getter for <code>my-cms.teacher.office</code>. 办公室
     */
    public String getOffice();

    /**
     * Setter for <code>my-cms.teacher.academy</code>. 所在学院
     */
    public ITeacher setAcademy(String value);

    /**
     * Getter for <code>my-cms.teacher.academy</code>. 所在学院
     */
    public String getAcademy();

    /**
     * Setter for <code>my-cms.teacher.created_at</code>. 创建时间
     */
    public ITeacher setCreatedAt(Timestamp value);

    /**
     * Getter for <code>my-cms.teacher.created_at</code>. 创建时间
     */
    public Timestamp getCreatedAt();

    /**
     * Setter for <code>my-cms.teacher.update_at</code>. 更新时间
     */
    public ITeacher setUpdateAt(Timestamp value);

    /**
     * Getter for <code>my-cms.teacher.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITeacher
     */
    public void from(com.vzard.mycms.database.tables.interfaces.ITeacher from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITeacher
     */
    public <E extends com.vzard.mycms.database.tables.interfaces.ITeacher> E into(E into);
}
