/*
 * This file is generated by jOOQ.
*/
package com.vzard.mycms.database.tables.records;


import com.vzard.mycms.database.tables.Grade;
import com.vzard.mycms.database.tables.interfaces.IGrade;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GradeRecord extends UpdatableRecordImpl<GradeRecord> implements Record8<Long, String, String, String, String, String, Timestamp, Timestamp>, IGrade {

    private static final long serialVersionUID = -1794252741;

    /**
     * Setter for <code>my-cms.grade.id</code>. id
     */
    @Override
    public GradeRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>my-cms.grade.id</code>. id
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>my-cms.grade.student_num</code>. 学号
     */
    @Override
    public GradeRecord setStudentNum(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>my-cms.grade.student_num</code>. 学号
     */
    @Override
    public String getStudentNum() {
        return (String) get(1);
    }

    /**
     * Setter for <code>my-cms.grade.course_num</code>. 课程号
     */
    @Override
    public GradeRecord setCourseNum(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>my-cms.grade.course_num</code>. 课程号
     */
    @Override
    public String getCourseNum() {
        return (String) get(2);
    }

    /**
     * Setter for <code>my-cms.grade.pacific_grade</code>. 平时成绩
     */
    @Override
    public GradeRecord setPacificGrade(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>my-cms.grade.pacific_grade</code>. 平时成绩
     */
    @Override
    public String getPacificGrade() {
        return (String) get(3);
    }

    /**
     * Setter for <code>my-cms.grade.paper_grade</code>. 卷面成绩
     */
    @Override
    public GradeRecord setPaperGrade(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>my-cms.grade.paper_grade</code>. 卷面成绩
     */
    @Override
    public String getPaperGrade() {
        return (String) get(4);
    }

    /**
     * Setter for <code>my-cms.grade.overall_grade</code>. 总评成绩
     */
    @Override
    public GradeRecord setOverallGrade(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>my-cms.grade.overall_grade</code>. 总评成绩
     */
    @Override
    public String getOverallGrade() {
        return (String) get(5);
    }

    /**
     * Setter for <code>my-cms.grade.created_at</code>. 创建时间
     */
    @Override
    public GradeRecord setCreatedAt(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>my-cms.grade.created_at</code>. 创建时间
     */
    @Override
    public Timestamp getCreatedAt() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>my-cms.grade.updated_at</code>. 更新时间
     */
    @Override
    public GradeRecord setUpdatedAt(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>my-cms.grade.updated_at</code>. 更新时间
     */
    @Override
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Grade.GRADE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Grade.GRADE.STUDENT_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Grade.GRADE.COURSE_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Grade.GRADE.PACIFIC_GRADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Grade.GRADE.PAPER_GRADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Grade.GRADE.OVERALL_GRADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Grade.GRADE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Grade.GRADE.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStudentNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCourseNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPacificGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPaperGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getOverallGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GradeRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GradeRecord value2(String value) {
        setStudentNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GradeRecord value3(String value) {
        setCourseNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GradeRecord value4(String value) {
        setPacificGrade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GradeRecord value5(String value) {
        setPaperGrade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GradeRecord value6(String value) {
        setOverallGrade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GradeRecord value7(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GradeRecord value8(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GradeRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IGrade from) {
        setId(from.getId());
        setStudentNum(from.getStudentNum());
        setCourseNum(from.getCourseNum());
        setPacificGrade(from.getPacificGrade());
        setPaperGrade(from.getPaperGrade());
        setOverallGrade(from.getOverallGrade());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IGrade> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GradeRecord
     */
    public GradeRecord() {
        super(Grade.GRADE);
    }

    /**
     * Create a detached, initialised GradeRecord
     */
    public GradeRecord(Long id, String studentNum, String courseNum, String pacificGrade, String paperGrade, String overallGrade, Timestamp createdAt, Timestamp updatedAt) {
        super(Grade.GRADE);

        set(0, id);
        set(1, studentNum);
        set(2, courseNum);
        set(3, pacificGrade);
        set(4, paperGrade);
        set(5, overallGrade);
        set(6, createdAt);
        set(7, updatedAt);
    }
}
