/*
 * This file is generated by jOOQ.
*/
package com.vzard.educms.database.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICourse extends Serializable {

    /**
     * Setter for <code>edu-cms.course.number</code>. 课程号
     */
    public ICourse setNumber(String value);

    /**
     * Getter for <code>edu-cms.course.number</code>. 课程号
     */
    public String getNumber();

    /**
     * Setter for <code>edu-cms.course.name</code>. 课程名称
     */
    public ICourse setName(String value);

    /**
     * Getter for <code>edu-cms.course.name</code>. 课程名称
     */
    public String getName();

    /**
     * Setter for <code>edu-cms.course.credit</code>. 学分
     */
    public ICourse setCredit(String value);

    /**
     * Getter for <code>edu-cms.course.credit</code>. 学分
     */
    public String getCredit();

    /**
     * Setter for <code>edu-cms.course.peried</code>. 课时
     */
    public ICourse setPeried(String value);

    /**
     * Getter for <code>edu-cms.course.peried</code>. 课时
     */
    public String getPeried();

    /**
     * Setter for <code>edu-cms.course.classroom</code>. 教室
     */
    public ICourse setClassroom(String value);

    /**
     * Getter for <code>edu-cms.course.classroom</code>. 教室
     */
    public String getClassroom();

    /**
     * Setter for <code>edu-cms.course.teacher</code>.
     */
    public ICourse setTeacher(String value);

    /**
     * Getter for <code>edu-cms.course.teacher</code>.
     */
    public String getTeacher();

    /**
     * Setter for <code>edu-cms.course.course_time</code>. 上课时间
     */
    public ICourse setCourseTime(String value);

    /**
     * Getter for <code>edu-cms.course.course_time</code>. 上课时间
     */
    public String getCourseTime();

    /**
     * Setter for <code>edu-cms.course.max_choosed</code>. 人数上限
     */
    public ICourse setMaxChoosed(String value);

    /**
     * Getter for <code>edu-cms.course.max_choosed</code>. 人数上限
     */
    public String getMaxChoosed();

    /**
     * Setter for <code>edu-cms.course.has_choosed</code>. 已选人数
     */
    public ICourse setHasChoosed(String value);

    /**
     * Getter for <code>edu-cms.course.has_choosed</code>. 已选人数
     */
    public String getHasChoosed();

    /**
     * Setter for <code>edu-cms.course.grade</code>. 考试成绩
     */
    public ICourse setGrade(String value);

    /**
     * Getter for <code>edu-cms.course.grade</code>. 考试成绩
     */
    public String getGrade();

    /**
     * Setter for <code>edu-cms.course.pacific_grade</code>. 平时成绩
     */
    public ICourse setPacificGrade(String value);

    /**
     * Getter for <code>edu-cms.course.pacific_grade</code>. 平时成绩
     */
    public String getPacificGrade();

    /**
     * Setter for <code>edu-cms.course.general_grade</code>. 总评成绩
     */
    public ICourse setGeneralGrade(String value);

    /**
     * Getter for <code>edu-cms.course.general_grade</code>. 总评成绩
     */
    public String getGeneralGrade();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICourse
     */
    public void from(com.vzard.educms.database.tables.interfaces.ICourse from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICourse
     */
    public <E extends com.vzard.educms.database.tables.interfaces.ICourse> E into(E into);
}
