/*
 * This file is generated by jOOQ.
*/
package com.vzard.educms.database.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IStudentCourse extends Serializable {

    /**
     * Setter for <code>edu-cms.student_course.id</code>. id
     */
    public IStudentCourse setId(Long value);

    /**
     * Getter for <code>edu-cms.student_course.id</code>. id
     */
    public Long getId();

    /**
     * Setter for <code>edu-cms.student_course.student_number</code>. 学生编号
     */
    public IStudentCourse setStudentNumber(String value);

    /**
     * Getter for <code>edu-cms.student_course.student_number</code>. 学生编号
     */
    public String getStudentNumber();

    /**
     * Setter for <code>edu-cms.student_course.course_number</code>. 课程编号
     */
    public IStudentCourse setCourseNumber(String value);

    /**
     * Getter for <code>edu-cms.student_course.course_number</code>. 课程编号
     */
    public String getCourseNumber();

    /**
     * Setter for <code>edu-cms.student_course.created_at</code>.
     */
    public IStudentCourse setCreatedAt(Timestamp value);

    /**
     * Getter for <code>edu-cms.student_course.created_at</code>.
     */
    public Timestamp getCreatedAt();

    /**
     * Setter for <code>edu-cms.student_course.updated_at</code>.
     */
    public IStudentCourse setUpdatedAt(Timestamp value);

    /**
     * Getter for <code>edu-cms.student_course.updated_at</code>.
     */
    public Timestamp getUpdatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IStudentCourse
     */
    public void from(com.vzard.educms.database.tables.interfaces.IStudentCourse from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IStudentCourse
     */
    public <E extends com.vzard.educms.database.tables.interfaces.IStudentCourse> E into(E into);
}
