/*
 * This file is generated by jOOQ.
*/
package com.vzard.educms.database.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITeacher extends Serializable {

    /**
     * Setter for <code>edu-cms.teacher.number</code>.
     */
    public ITeacher setNumber(String value);

    /**
     * Getter for <code>edu-cms.teacher.number</code>.
     */
    public String getNumber();

    /**
     * Setter for <code>edu-cms.teacher.name</code>.
     */
    public ITeacher setName(String value);

    /**
     * Getter for <code>edu-cms.teacher.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>edu-cms.teacher.office</code>.
     */
    public ITeacher setOffice(String value);

    /**
     * Getter for <code>edu-cms.teacher.office</code>.
     */
    public String getOffice();

    /**
     * Setter for <code>edu-cms.teacher.title</code>.
     */
    public ITeacher setTitle(String value);

    /**
     * Getter for <code>edu-cms.teacher.title</code>.
     */
    public String getTitle();

    /**
     * Setter for <code>edu-cms.teacher.phone_number</code>.
     */
    public ITeacher setPhoneNumber(String value);

    /**
     * Getter for <code>edu-cms.teacher.phone_number</code>.
     */
    public String getPhoneNumber();

    /**
     * Setter for <code>edu-cms.teacher.gender</code>.
     */
    public ITeacher setGender(String value);

    /**
     * Getter for <code>edu-cms.teacher.gender</code>.
     */
    public String getGender();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITeacher
     */
    public void from(com.vzard.educms.database.tables.interfaces.ITeacher from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITeacher
     */
    public <E extends com.vzard.educms.database.tables.interfaces.ITeacher> E into(E into);
}
