/*
 * This file is generated by jOOQ.
*/
package com.vzard.educms.database.tables.records;


import com.vzard.educms.database.tables.Course;
import com.vzard.educms.database.tables.interfaces.ICourse;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CourseRecord extends UpdatableRecordImpl<CourseRecord> implements Record12<String, String, String, String, String, String, String, String, String, String, String, String>, ICourse {

    private static final long serialVersionUID = 1267486073;

    /**
     * Setter for <code>edu-cms.course.number</code>. 课程号
     */
    @Override
    public CourseRecord setNumber(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.course.number</code>. 课程号
     */
    @Override
    public String getNumber() {
        return (String) get(0);
    }

    /**
     * Setter for <code>edu-cms.course.name</code>. 课程名称
     */
    @Override
    public CourseRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.course.name</code>. 课程名称
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>edu-cms.course.credit</code>. 学分
     */
    @Override
    public CourseRecord setCredit(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.course.credit</code>. 学分
     */
    @Override
    public String getCredit() {
        return (String) get(2);
    }

    /**
     * Setter for <code>edu-cms.course.peried</code>. 课时
     */
    @Override
    public CourseRecord setPeried(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.course.peried</code>. 课时
     */
    @Override
    public String getPeried() {
        return (String) get(3);
    }

    /**
     * Setter for <code>edu-cms.course.classroom</code>. 教室
     */
    @Override
    public CourseRecord setClassroom(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.course.classroom</code>. 教室
     */
    @Override
    public String getClassroom() {
        return (String) get(4);
    }

    /**
     * Setter for <code>edu-cms.course.teacher</code>.
     */
    @Override
    public CourseRecord setTeacher(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.course.teacher</code>.
     */
    @Override
    public String getTeacher() {
        return (String) get(5);
    }

    /**
     * Setter for <code>edu-cms.course.course_time</code>. 上课时间
     */
    @Override
    public CourseRecord setCourseTime(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.course.course_time</code>. 上课时间
     */
    @Override
    public String getCourseTime() {
        return (String) get(6);
    }

    /**
     * Setter for <code>edu-cms.course.max_choosed</code>. 人数上限
     */
    @Override
    public CourseRecord setMaxChoosed(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.course.max_choosed</code>. 人数上限
     */
    @Override
    public String getMaxChoosed() {
        return (String) get(7);
    }

    /**
     * Setter for <code>edu-cms.course.has_choosed</code>. 已选人数
     */
    @Override
    public CourseRecord setHasChoosed(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.course.has_choosed</code>. 已选人数
     */
    @Override
    public String getHasChoosed() {
        return (String) get(8);
    }

    /**
     * Setter for <code>edu-cms.course.grade</code>. 考试成绩
     */
    @Override
    public CourseRecord setGrade(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.course.grade</code>. 考试成绩
     */
    @Override
    public String getGrade() {
        return (String) get(9);
    }

    /**
     * Setter for <code>edu-cms.course.pacific_grade</code>. 平时成绩
     */
    @Override
    public CourseRecord setPacificGrade(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.course.pacific_grade</code>. 平时成绩
     */
    @Override
    public String getPacificGrade() {
        return (String) get(10);
    }

    /**
     * Setter for <code>edu-cms.course.general_grade</code>. 总评成绩
     */
    @Override
    public CourseRecord setGeneralGrade(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.course.general_grade</code>. 总评成绩
     */
    @Override
    public String getGeneralGrade() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Course.COURSE.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Course.COURSE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Course.COURSE.CREDIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Course.COURSE.PERIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Course.COURSE.CLASSROOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Course.COURSE.TEACHER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Course.COURSE.COURSE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Course.COURSE.MAX_CHOOSED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Course.COURSE.HAS_CHOOSED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Course.COURSE.GRADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Course.COURSE.PACIFIC_GRADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Course.COURSE.GENERAL_GRADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCredit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPeried();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getClassroom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTeacher();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCourseTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getMaxChoosed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getHasChoosed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getPacificGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getGeneralGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value1(String value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value3(String value) {
        setCredit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value4(String value) {
        setPeried(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value5(String value) {
        setClassroom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value6(String value) {
        setTeacher(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value7(String value) {
        setCourseTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value8(String value) {
        setMaxChoosed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value9(String value) {
        setHasChoosed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value10(String value) {
        setGrade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value11(String value) {
        setPacificGrade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value12(String value) {
        setGeneralGrade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ICourse from) {
        setNumber(from.getNumber());
        setName(from.getName());
        setCredit(from.getCredit());
        setPeried(from.getPeried());
        setClassroom(from.getClassroom());
        setTeacher(from.getTeacher());
        setCourseTime(from.getCourseTime());
        setMaxChoosed(from.getMaxChoosed());
        setHasChoosed(from.getHasChoosed());
        setGrade(from.getGrade());
        setPacificGrade(from.getPacificGrade());
        setGeneralGrade(from.getGeneralGrade());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ICourse> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CourseRecord
     */
    public CourseRecord() {
        super(Course.COURSE);
    }

    /**
     * Create a detached, initialised CourseRecord
     */
    public CourseRecord(String number, String name, String credit, String peried, String classroom, String teacher, String courseTime, String maxChoosed, String hasChoosed, String grade, String pacificGrade, String generalGrade) {
        super(Course.COURSE);

        set(0, number);
        set(1, name);
        set(2, credit);
        set(3, peried);
        set(4, classroom);
        set(5, teacher);
        set(6, courseTime);
        set(7, maxChoosed);
        set(8, hasChoosed);
        set(9, grade);
        set(10, pacificGrade);
        set(11, generalGrade);
    }
}
