/*
 * This file is generated by jOOQ.
*/
package com.vzard.educms.database.tables.records;


import com.vzard.educms.database.tables.Teacher;
import com.vzard.educms.database.tables.interfaces.ITeacher;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherRecord extends TableRecordImpl<TeacherRecord> implements Record6<String, String, String, String, String, String>, ITeacher {

    private static final long serialVersionUID = 8519751;

    /**
     * Setter for <code>edu-cms.teacher.number</code>.
     */
    @Override
    public TeacherRecord setNumber(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.teacher.number</code>.
     */
    @Override
    public String getNumber() {
        return (String) get(0);
    }

    /**
     * Setter for <code>edu-cms.teacher.name</code>.
     */
    @Override
    public TeacherRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.teacher.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>edu-cms.teacher.office</code>.
     */
    @Override
    public TeacherRecord setOffice(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.teacher.office</code>.
     */
    @Override
    public String getOffice() {
        return (String) get(2);
    }

    /**
     * Setter for <code>edu-cms.teacher.title</code>.
     */
    @Override
    public TeacherRecord setTitle(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.teacher.title</code>.
     */
    @Override
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>edu-cms.teacher.phone_number</code>.
     */
    @Override
    public TeacherRecord setPhoneNumber(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.teacher.phone_number</code>.
     */
    @Override
    public String getPhoneNumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>edu-cms.teacher.gender</code>.
     */
    @Override
    public TeacherRecord setGender(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>edu-cms.teacher.gender</code>.
     */
    @Override
    public String getGender() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Teacher.TEACHER.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Teacher.TEACHER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Teacher.TEACHER.OFFICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Teacher.TEACHER.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Teacher.TEACHER.PHONE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Teacher.TEACHER.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOffice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeacherRecord value1(String value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeacherRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeacherRecord value3(String value) {
        setOffice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeacherRecord value4(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeacherRecord value5(String value) {
        setPhoneNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeacherRecord value6(String value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeacherRecord values(String value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITeacher from) {
        setNumber(from.getNumber());
        setName(from.getName());
        setOffice(from.getOffice());
        setTitle(from.getTitle());
        setPhoneNumber(from.getPhoneNumber());
        setGender(from.getGender());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITeacher> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeacherRecord
     */
    public TeacherRecord() {
        super(Teacher.TEACHER);
    }

    /**
     * Create a detached, initialised TeacherRecord
     */
    public TeacherRecord(String number, String name, String office, String title, String phoneNumber, String gender) {
        super(Teacher.TEACHER);

        set(0, number);
        set(1, name);
        set(2, office);
        set(3, title);
        set(4, phoneNumber);
        set(5, gender);
    }
}
