/*
 * This file is generated by jOOQ.
*/
package com.vzard.educms.database;


import com.vzard.educms.database.tables.Course;
import com.vzard.educms.database.tables.Student;
import com.vzard.educms.database.tables.Teacher;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduCms extends SchemaImpl {

    private static final long serialVersionUID = 1383271970;

    /**
     * The reference instance of <code>edu-cms</code>
     */
    public static final EduCms EDU_CMS = new EduCms();

    /**
     * The table <code>edu-cms.course</code>.
     */
    public final Course COURSE = com.vzard.educms.database.tables.Course.COURSE;

    /**
     * The table <code>edu-cms.student</code>.
     */
    public final Student STUDENT = com.vzard.educms.database.tables.Student.STUDENT;

    /**
     * The table <code>edu-cms.teacher</code>.
     */
    public final Teacher TEACHER = com.vzard.educms.database.tables.Teacher.TEACHER;

    /**
     * No further instances allowed
     */
    private EduCms() {
        super("edu-cms", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Course.COURSE,
            Student.STUDENT,
            Teacher.TEACHER);
    }
}
