/*
 * This file is generated by jOOQ.
*/
package com.vzard.educms.database;


import com.vzard.educms.database.tables.Course;
import com.vzard.educms.database.tables.Student;
import com.vzard.educms.database.tables.Teacher;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in edu-cms
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>edu-cms.course</code>.
     */
    public static final Course COURSE = com.vzard.educms.database.tables.Course.COURSE;

    /**
     * The table <code>edu-cms.student</code>.
     */
    public static final Student STUDENT = com.vzard.educms.database.tables.Student.STUDENT;

    /**
     * The table <code>edu-cms.teacher</code>.
     */
    public static final Teacher TEACHER = com.vzard.educms.database.tables.Teacher.TEACHER;
}
