/*
 * This file is generated by jOOQ.
*/
package com.vzard.mycms.database.tables.pojos;


import com.vzard.mycms.database.tables.interfaces.IAdmin;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Admin implements IAdmin {

    private static final long serialVersionUID = -755672689;

    private Integer   id;
    private String    number;
    private String    name;
    private String    password;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public Admin() {}

    public Admin(Admin value) {
        this.id = value.id;
        this.number = value.number;
        this.name = value.name;
        this.password = value.password;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Admin(
        Integer   id,
        String    number,
        String    name,
        String    password,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.number = number;
        this.name = name;
        this.password = password;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public Admin setId(Integer id) {
        this.id = id;
        return this;
    }

    @Override
    public String getNumber() {
        return this.number;
    }

    @Override
    public Admin setNumber(String number) {
        this.number = number;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public Admin setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public Admin setPassword(String password) {
        this.password = password;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public Admin setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public Admin setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Admin (");

        sb.append(id);
        sb.append(", ").append(number);
        sb.append(", ").append(name);
        sb.append(", ").append(password);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IAdmin from) {
        setId(from.getId());
        setNumber(from.getNumber());
        setName(from.getName());
        setPassword(from.getPassword());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IAdmin> E into(E into) {
        into.from(this);
        return into;
    }
}
