/*
 * This file is generated by jOOQ.
*/
package com.vzard.mycms.database.tables.pojos;


import com.vzard.mycms.database.tables.interfaces.IStudentCourse;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentCourse implements IStudentCourse {

    private static final long serialVersionUID = 218163148;

    private Long      id;
    private Long      studentNum;
    private Long      courseNum;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public StudentCourse() {}

    public StudentCourse(StudentCourse value) {
        this.id = value.id;
        this.studentNum = value.studentNum;
        this.courseNum = value.courseNum;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public StudentCourse(
        Long      id,
        Long      studentNum,
        Long      courseNum,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.studentNum = studentNum;
        this.courseNum = courseNum;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public StudentCourse setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public Long getStudentNum() {
        return this.studentNum;
    }

    @Override
    public StudentCourse setStudentNum(Long studentNum) {
        this.studentNum = studentNum;
        return this;
    }

    @Override
    public Long getCourseNum() {
        return this.courseNum;
    }

    @Override
    public StudentCourse setCourseNum(Long courseNum) {
        this.courseNum = courseNum;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public StudentCourse setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public StudentCourse setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StudentCourse (");

        sb.append(id);
        sb.append(", ").append(studentNum);
        sb.append(", ").append(courseNum);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IStudentCourse from) {
        setId(from.getId());
        setStudentNum(from.getStudentNum());
        setCourseNum(from.getCourseNum());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IStudentCourse> E into(E into) {
        into.from(this);
        return into;
    }
}
