/*
 * This file is generated by jOOQ.
*/
package com.vzard.mycms.database.tables.pojos;


import com.vzard.mycms.database.tables.interfaces.ITeacher;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Teacher implements ITeacher {

    private static final long serialVersionUID = -1743934559;

    private Long      number;
    private String    name;
    private String    password;
    private String    gender;
    private String    office;
    private String    academy;
    private Timestamp createdAt;
    private Timestamp updateAt;

    public Teacher() {}

    public Teacher(Teacher value) {
        this.number = value.number;
        this.name = value.name;
        this.password = value.password;
        this.gender = value.gender;
        this.office = value.office;
        this.academy = value.academy;
        this.createdAt = value.createdAt;
        this.updateAt = value.updateAt;
    }

    public Teacher(
        Long      number,
        String    name,
        String    password,
        String    gender,
        String    office,
        String    academy,
        Timestamp createdAt,
        Timestamp updateAt
    ) {
        this.number = number;
        this.name = name;
        this.password = password;
        this.gender = gender;
        this.office = office;
        this.academy = academy;
        this.createdAt = createdAt;
        this.updateAt = updateAt;
    }

    @Override
    public Long getNumber() {
        return this.number;
    }

    @Override
    public Teacher setNumber(Long number) {
        this.number = number;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public Teacher setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public Teacher setPassword(String password) {
        this.password = password;
        return this;
    }

    @Override
    public String getGender() {
        return this.gender;
    }

    @Override
    public Teacher setGender(String gender) {
        this.gender = gender;
        return this;
    }

    @Override
    public String getOffice() {
        return this.office;
    }

    @Override
    public Teacher setOffice(String office) {
        this.office = office;
        return this;
    }

    @Override
    public String getAcademy() {
        return this.academy;
    }

    @Override
    public Teacher setAcademy(String academy) {
        this.academy = academy;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public Teacher setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    @Override
    public Teacher setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Teacher (");

        sb.append(number);
        sb.append(", ").append(name);
        sb.append(", ").append(password);
        sb.append(", ").append(gender);
        sb.append(", ").append(office);
        sb.append(", ").append(academy);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updateAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITeacher from) {
        setNumber(from.getNumber());
        setName(from.getName());
        setPassword(from.getPassword());
        setGender(from.getGender());
        setOffice(from.getOffice());
        setAcademy(from.getAcademy());
        setCreatedAt(from.getCreatedAt());
        setUpdateAt(from.getUpdateAt());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITeacher> E into(E into) {
        into.from(this);
        return into;
    }
}
