/*
 * This file is generated by jOOQ.
*/
package com.vzard.mycms.database.tables.pojos;


import com.vzard.mycms.database.tables.interfaces.ITeacherCourse;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherCourse implements ITeacherCourse {

    private static final long serialVersionUID = 2097257382;

    private Long      id;
    private String    teacherNum;
    private String    courseNum;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public TeacherCourse() {}

    public TeacherCourse(TeacherCourse value) {
        this.id = value.id;
        this.teacherNum = value.teacherNum;
        this.courseNum = value.courseNum;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public TeacherCourse(
        Long      id,
        String    teacherNum,
        String    courseNum,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.teacherNum = teacherNum;
        this.courseNum = courseNum;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TeacherCourse setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getTeacherNum() {
        return this.teacherNum;
    }

    @Override
    public TeacherCourse setTeacherNum(String teacherNum) {
        this.teacherNum = teacherNum;
        return this;
    }

    @Override
    public String getCourseNum() {
        return this.courseNum;
    }

    @Override
    public TeacherCourse setCourseNum(String courseNum) {
        this.courseNum = courseNum;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public TeacherCourse setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public TeacherCourse setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TeacherCourse (");

        sb.append(id);
        sb.append(", ").append(teacherNum);
        sb.append(", ").append(courseNum);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITeacherCourse from) {
        setId(from.getId());
        setTeacherNum(from.getTeacherNum());
        setCourseNum(from.getCourseNum());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITeacherCourse> E into(E into) {
        into.from(this);
        return into;
    }
}
