/*
 * This file is generated by jOOQ.
*/
package com.vzard.mycms.database;


import com.vzard.mycms.database.tables.Admin;
import com.vzard.mycms.database.tables.Course;
import com.vzard.mycms.database.tables.Grade;
import com.vzard.mycms.database.tables.Student;
import com.vzard.mycms.database.tables.StudentCourse;
import com.vzard.mycms.database.tables.Teacher;
import com.vzard.mycms.database.tables.TeacherCourse;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MyCms extends SchemaImpl {

    private static final long serialVersionUID = -2122872804;

    /**
     * The reference instance of <code>my-cms</code>
     */
    public static final MyCms MY_CMS = new MyCms();

    /**
     * The table <code>my-cms.admin</code>.
     */
    public final Admin ADMIN = com.vzard.mycms.database.tables.Admin.ADMIN;

    /**
     * The table <code>my-cms.course</code>.
     */
    public final Course COURSE = com.vzard.mycms.database.tables.Course.COURSE;

    /**
     * The table <code>my-cms.grade</code>.
     */
    public final Grade GRADE = com.vzard.mycms.database.tables.Grade.GRADE;

    /**
     * The table <code>my-cms.student</code>.
     */
    public final Student STUDENT = com.vzard.mycms.database.tables.Student.STUDENT;

    /**
     * The table <code>my-cms.student_course</code>.
     */
    public final StudentCourse STUDENT_COURSE = com.vzard.mycms.database.tables.StudentCourse.STUDENT_COURSE;

    /**
     * The table <code>my-cms.teacher</code>.
     */
    public final Teacher TEACHER = com.vzard.mycms.database.tables.Teacher.TEACHER;

    /**
     * The table <code>my-cms.teacher_course</code>.
     */
    public final TeacherCourse TEACHER_COURSE = com.vzard.mycms.database.tables.TeacherCourse.TEACHER_COURSE;

    /**
     * No further instances allowed
     */
    private MyCms() {
        super("my-cms", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Admin.ADMIN,
            Course.COURSE,
            Grade.GRADE,
            Student.STUDENT,
            StudentCourse.STUDENT_COURSE,
            Teacher.TEACHER,
            TeacherCourse.TEACHER_COURSE);
    }
}
