/*
 * This file is generated by jOOQ.
*/
package com.vzard.mycms.database;


import com.vzard.mycms.database.tables.Admin;
import com.vzard.mycms.database.tables.Course;
import com.vzard.mycms.database.tables.Grade;
import com.vzard.mycms.database.tables.Student;
import com.vzard.mycms.database.tables.StudentCourse;
import com.vzard.mycms.database.tables.Teacher;
import com.vzard.mycms.database.tables.TeacherCourse;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in my-cms
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>my-cms.admin</code>.
     */
    public static final Admin ADMIN = com.vzard.mycms.database.tables.Admin.ADMIN;

    /**
     * The table <code>my-cms.course</code>.
     */
    public static final Course COURSE = com.vzard.mycms.database.tables.Course.COURSE;

    /**
     * The table <code>my-cms.grade</code>.
     */
    public static final Grade GRADE = com.vzard.mycms.database.tables.Grade.GRADE;

    /**
     * The table <code>my-cms.student</code>.
     */
    public static final Student STUDENT = com.vzard.mycms.database.tables.Student.STUDENT;

    /**
     * The table <code>my-cms.student_course</code>.
     */
    public static final StudentCourse STUDENT_COURSE = com.vzard.mycms.database.tables.StudentCourse.STUDENT_COURSE;

    /**
     * The table <code>my-cms.teacher</code>.
     */
    public static final Teacher TEACHER = com.vzard.mycms.database.tables.Teacher.TEACHER;

    /**
     * The table <code>my-cms.teacher_course</code>.
     */
    public static final TeacherCourse TEACHER_COURSE = com.vzard.mycms.database.tables.TeacherCourse.TEACHER_COURSE;
}
