/*
 * This file is generated by jOOQ.
*/
package com.vzard.educms.database.tables;


import com.vzard.educms.database.EduCms;
import com.vzard.educms.database.tables.records.CourseRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Course extends TableImpl<CourseRecord> {

    private static final long serialVersionUID = -610706695;

    /**
     * The reference instance of <code>edu-cms.course</code>
     */
    public static final Course COURSE = new Course();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CourseRecord> getRecordType() {
        return CourseRecord.class;
    }

    /**
     * The column <code>edu-cms.course.number</code>. 课程号
     */
    public final TableField<CourseRecord, String> NUMBER = createField("number", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "课程号");

    /**
     * The column <code>edu-cms.course.name</code>. 课程名称
     */
    public final TableField<CourseRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "课程名称");

    /**
     * The column <code>edu-cms.course.credit</code>. 学分
     */
    public final TableField<CourseRecord, String> CREDIT = createField("credit", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "学分");

    /**
     * The column <code>edu-cms.course.peried</code>. 课时
     */
    public final TableField<CourseRecord, String> PERIED = createField("peried", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "课时");

    /**
     * The column <code>edu-cms.course.classroom</code>. 教室
     */
    public final TableField<CourseRecord, String> CLASSROOM = createField("classroom", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "教室");

    /**
     * The column <code>edu-cms.course.course_time</code>. 上课时间
     */
    public final TableField<CourseRecord, String> COURSE_TIME = createField("course_time", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "上课时间");

    /**
     * The column <code>edu-cms.course.max_choosed</code>. 人数上限
     */
    public final TableField<CourseRecord, String> MAX_CHOOSED = createField("max_choosed", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "人数上限");

    /**
     * The column <code>edu-cms.course.has_choosed</code>. 已选人数
     */
    public final TableField<CourseRecord, String> HAS_CHOOSED = createField("has_choosed", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "已选人数");

    /**
     * The column <code>edu-cms.course.grade</code>. 考试成绩
     */
    public final TableField<CourseRecord, String> GRADE = createField("grade", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "考试成绩");

    /**
     * The column <code>edu-cms.course.pacific_grade</code>. 平时成绩
     */
    public final TableField<CourseRecord, String> PACIFIC_GRADE = createField("pacific_grade", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "平时成绩");

    /**
     * The column <code>edu-cms.course.general_grade</code>. 总评成绩
     */
    public final TableField<CourseRecord, String> GENERAL_GRADE = createField("general_grade", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "总评成绩");

    /**
     * Create a <code>edu-cms.course</code> table reference
     */
    public Course() {
        this("course", null);
    }

    /**
     * Create an aliased <code>edu-cms.course</code> table reference
     */
    public Course(String alias) {
        this(alias, COURSE);
    }

    private Course(String alias, Table<CourseRecord> aliased) {
        this(alias, aliased, null);
    }

    private Course(String alias, Table<CourseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return EduCms.EDU_CMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Course as(String alias) {
        return new Course(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Course rename(String name) {
        return new Course(name, null);
    }
}
