/*
 * This file is generated by jOOQ.
*/
package com.vzard.educms.database.tables;


import com.vzard.educms.database.EduCms;
import com.vzard.educms.database.Keys;
import com.vzard.educms.database.tables.records.StudentCourseRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentCourse extends TableImpl<StudentCourseRecord> {

    private static final long serialVersionUID = -1506190828;

    /**
     * The reference instance of <code>edu-cms.student_course</code>
     */
    public static final StudentCourse STUDENT_COURSE = new StudentCourse();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StudentCourseRecord> getRecordType() {
        return StudentCourseRecord.class;
    }

    /**
     * The column <code>edu-cms.student_course.id</code>. id
     */
    public final TableField<StudentCourseRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "id");

    /**
     * The column <code>edu-cms.student_course.student_number</code>. 学生编号
     */
    public final TableField<StudentCourseRecord, String> STUDENT_NUMBER = createField("student_number", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "学生编号");

    /**
     * The column <code>edu-cms.student_course.course_number</code>. 课程编号
     */
    public final TableField<StudentCourseRecord, String> COURSE_NUMBER = createField("course_number", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "课程编号");

    /**
     * The column <code>edu-cms.student_course.created_at</code>.
     */
    public final TableField<StudentCourseRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP(3)", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>edu-cms.student_course.updated_at</code>.
     */
    public final TableField<StudentCourseRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00.000", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>edu-cms.student_course</code> table reference
     */
    public StudentCourse() {
        this("student_course", null);
    }

    /**
     * Create an aliased <code>edu-cms.student_course</code> table reference
     */
    public StudentCourse(String alias) {
        this(alias, STUDENT_COURSE);
    }

    private StudentCourse(String alias, Table<StudentCourseRecord> aliased) {
        this(alias, aliased, null);
    }

    private StudentCourse(String alias, Table<StudentCourseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return EduCms.EDU_CMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StudentCourseRecord> getPrimaryKey() {
        return Keys.KEY_STUDENT_COURSE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StudentCourseRecord>> getKeys() {
        return Arrays.<UniqueKey<StudentCourseRecord>>asList(Keys.KEY_STUDENT_COURSE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentCourse as(String alias) {
        return new StudentCourse(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StudentCourse rename(String name) {
        return new StudentCourse(name, null);
    }
}
