/*
 * This file is generated by jOOQ.
*/
package com.vzard.educms.database.tables;


import com.vzard.educms.database.EduCms;
import com.vzard.educms.database.Keys;
import com.vzard.educms.database.tables.records.TeacherCourseRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherCourse extends TableImpl<TeacherCourseRecord> {

    private static final long serialVersionUID = 521996437;

    /**
     * The reference instance of <code>edu-cms.teacher_course</code>
     */
    public static final TeacherCourse TEACHER_COURSE = new TeacherCourse();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeacherCourseRecord> getRecordType() {
        return TeacherCourseRecord.class;
    }

    /**
     * The column <code>edu-cms.teacher_course.id</code>.
     */
    public final TableField<TeacherCourseRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>edu-cms.teacher_course.teacher_number</code>.
     */
    public final TableField<TeacherCourseRecord, String> TEACHER_NUMBER = createField("teacher_number", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>edu-cms.teacher_course.course_number</code>.
     */
    public final TableField<TeacherCourseRecord, String> COURSE_NUMBER = createField("course_number", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>edu-cms.teacher_course.created_at</code>.
     */
    public final TableField<TeacherCourseRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP(3)", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>edu-cms.teacher_course.updated_at</code>.
     */
    public final TableField<TeacherCourseRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00.000", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>edu-cms.teacher_course</code> table reference
     */
    public TeacherCourse() {
        this("teacher_course", null);
    }

    /**
     * Create an aliased <code>edu-cms.teacher_course</code> table reference
     */
    public TeacherCourse(String alias) {
        this(alias, TEACHER_COURSE);
    }

    private TeacherCourse(String alias, Table<TeacherCourseRecord> aliased) {
        this(alias, aliased, null);
    }

    private TeacherCourse(String alias, Table<TeacherCourseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return EduCms.EDU_CMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TeacherCourseRecord> getPrimaryKey() {
        return Keys.KEY_TEACHER_COURSE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TeacherCourseRecord>> getKeys() {
        return Arrays.<UniqueKey<TeacherCourseRecord>>asList(Keys.KEY_TEACHER_COURSE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeacherCourse as(String alias) {
        return new TeacherCourse(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TeacherCourse rename(String name) {
        return new TeacherCourse(name, null);
    }
}
