/*
 * This file is generated by jOOQ.
*/
package com.vzard.educms.database.tables;


import com.vzard.educms.database.EduCms;
import com.vzard.educms.database.tables.records.TeacherRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Teacher extends TableImpl<TeacherRecord> {

    private static final long serialVersionUID = 864749498;

    /**
     * The reference instance of <code>edu-cms.teacher</code>
     */
    public static final Teacher TEACHER = new Teacher();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeacherRecord> getRecordType() {
        return TeacherRecord.class;
    }

    /**
     * The column <code>edu-cms.teacher.number</code>.
     */
    public final TableField<TeacherRecord, String> NUMBER = createField("number", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>edu-cms.teacher.name</code>.
     */
    public final TableField<TeacherRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>edu-cms.teacher.office</code>.
     */
    public final TableField<TeacherRecord, String> OFFICE = createField("office", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>edu-cms.teacher.title</code>.
     */
    public final TableField<TeacherRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>edu-cms.teacher.phone_number</code>.
     */
    public final TableField<TeacherRecord, String> PHONE_NUMBER = createField("phone_number", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>edu-cms.teacher.gender</code>.
     */
    public final TableField<TeacherRecord, String> GENDER = createField("gender", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * Create a <code>edu-cms.teacher</code> table reference
     */
    public Teacher() {
        this("teacher", null);
    }

    /**
     * Create an aliased <code>edu-cms.teacher</code> table reference
     */
    public Teacher(String alias) {
        this(alias, TEACHER);
    }

    private Teacher(String alias, Table<TeacherRecord> aliased) {
        this(alias, aliased, null);
    }

    private Teacher(String alias, Table<TeacherRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return EduCms.EDU_CMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Teacher as(String alias) {
        return new Teacher(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Teacher rename(String name) {
        return new Teacher(name, null);
    }
}
