/*
 * This file is generated by jOOQ.
*/
package com.vzard.educms.database.tables.pojos;


import com.vzard.educms.database.tables.interfaces.ICourse;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Course implements ICourse {

    private static final long serialVersionUID = -1247258249;

    private String number;
    private String name;
    private String credit;
    private String peried;
    private String classroom;
    private String teacher;
    private String courseTime;
    private String maxChoosed;
    private String hasChoosed;
    private String grade;
    private String pacificGrade;
    private String generalGrade;

    public Course() {}

    public Course(Course value) {
        this.number = value.number;
        this.name = value.name;
        this.credit = value.credit;
        this.peried = value.peried;
        this.classroom = value.classroom;
        this.teacher = value.teacher;
        this.courseTime = value.courseTime;
        this.maxChoosed = value.maxChoosed;
        this.hasChoosed = value.hasChoosed;
        this.grade = value.grade;
        this.pacificGrade = value.pacificGrade;
        this.generalGrade = value.generalGrade;
    }

    public Course(
        String number,
        String name,
        String credit,
        String peried,
        String classroom,
        String teacher,
        String courseTime,
        String maxChoosed,
        String hasChoosed,
        String grade,
        String pacificGrade,
        String generalGrade
    ) {
        this.number = number;
        this.name = name;
        this.credit = credit;
        this.peried = peried;
        this.classroom = classroom;
        this.teacher = teacher;
        this.courseTime = courseTime;
        this.maxChoosed = maxChoosed;
        this.hasChoosed = hasChoosed;
        this.grade = grade;
        this.pacificGrade = pacificGrade;
        this.generalGrade = generalGrade;
    }

    @Override
    public String getNumber() {
        return this.number;
    }

    @Override
    public Course setNumber(String number) {
        this.number = number;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public Course setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getCredit() {
        return this.credit;
    }

    @Override
    public Course setCredit(String credit) {
        this.credit = credit;
        return this;
    }

    @Override
    public String getPeried() {
        return this.peried;
    }

    @Override
    public Course setPeried(String peried) {
        this.peried = peried;
        return this;
    }

    @Override
    public String getClassroom() {
        return this.classroom;
    }

    @Override
    public Course setClassroom(String classroom) {
        this.classroom = classroom;
        return this;
    }

    @Override
    public String getTeacher() {
        return this.teacher;
    }

    @Override
    public Course setTeacher(String teacher) {
        this.teacher = teacher;
        return this;
    }

    @Override
    public String getCourseTime() {
        return this.courseTime;
    }

    @Override
    public Course setCourseTime(String courseTime) {
        this.courseTime = courseTime;
        return this;
    }

    @Override
    public String getMaxChoosed() {
        return this.maxChoosed;
    }

    @Override
    public Course setMaxChoosed(String maxChoosed) {
        this.maxChoosed = maxChoosed;
        return this;
    }

    @Override
    public String getHasChoosed() {
        return this.hasChoosed;
    }

    @Override
    public Course setHasChoosed(String hasChoosed) {
        this.hasChoosed = hasChoosed;
        return this;
    }

    @Override
    public String getGrade() {
        return this.grade;
    }

    @Override
    public Course setGrade(String grade) {
        this.grade = grade;
        return this;
    }

    @Override
    public String getPacificGrade() {
        return this.pacificGrade;
    }

    @Override
    public Course setPacificGrade(String pacificGrade) {
        this.pacificGrade = pacificGrade;
        return this;
    }

    @Override
    public String getGeneralGrade() {
        return this.generalGrade;
    }

    @Override
    public Course setGeneralGrade(String generalGrade) {
        this.generalGrade = generalGrade;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Course (");

        sb.append(number);
        sb.append(", ").append(name);
        sb.append(", ").append(credit);
        sb.append(", ").append(peried);
        sb.append(", ").append(classroom);
        sb.append(", ").append(teacher);
        sb.append(", ").append(courseTime);
        sb.append(", ").append(maxChoosed);
        sb.append(", ").append(hasChoosed);
        sb.append(", ").append(grade);
        sb.append(", ").append(pacificGrade);
        sb.append(", ").append(generalGrade);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ICourse from) {
        setNumber(from.getNumber());
        setName(from.getName());
        setCredit(from.getCredit());
        setPeried(from.getPeried());
        setClassroom(from.getClassroom());
        setTeacher(from.getTeacher());
        setCourseTime(from.getCourseTime());
        setMaxChoosed(from.getMaxChoosed());
        setHasChoosed(from.getHasChoosed());
        setGrade(from.getGrade());
        setPacificGrade(from.getPacificGrade());
        setGeneralGrade(from.getGeneralGrade());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ICourse> E into(E into) {
        into.from(this);
        return into;
    }
}
