/*
 * This file is generated by jOOQ.
*/
package com.vzard.educms.database.tables.pojos;


import com.vzard.educms.database.tables.interfaces.IStudentCourse;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentCourse implements IStudentCourse {

    private static final long serialVersionUID = -674375794;

    private Long      id;
    private String    studentNumber;
    private String    courseNumber;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public StudentCourse() {}

    public StudentCourse(StudentCourse value) {
        this.id = value.id;
        this.studentNumber = value.studentNumber;
        this.courseNumber = value.courseNumber;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public StudentCourse(
        Long      id,
        String    studentNumber,
        String    courseNumber,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.studentNumber = studentNumber;
        this.courseNumber = courseNumber;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public StudentCourse setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getStudentNumber() {
        return this.studentNumber;
    }

    @Override
    public StudentCourse setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber;
        return this;
    }

    @Override
    public String getCourseNumber() {
        return this.courseNumber;
    }

    @Override
    public StudentCourse setCourseNumber(String courseNumber) {
        this.courseNumber = courseNumber;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public StudentCourse setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public StudentCourse setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StudentCourse (");

        sb.append(id);
        sb.append(", ").append(studentNumber);
        sb.append(", ").append(courseNumber);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IStudentCourse from) {
        setId(from.getId());
        setStudentNumber(from.getStudentNumber());
        setCourseNumber(from.getCourseNumber());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IStudentCourse> E into(E into) {
        into.from(this);
        return into;
    }
}
