/*
 * This file is generated by jOOQ.
*/
package com.vzard.educms.database.tables.pojos;


import com.vzard.educms.database.tables.interfaces.ITeacherCourse;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherCourse implements ITeacherCourse {

    private static final long serialVersionUID = -805196114;

    private Long      id;
    private String    teacherNumber;
    private String    courseNumber;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public TeacherCourse() {}

    public TeacherCourse(TeacherCourse value) {
        this.id = value.id;
        this.teacherNumber = value.teacherNumber;
        this.courseNumber = value.courseNumber;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public TeacherCourse(
        Long      id,
        String    teacherNumber,
        String    courseNumber,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.teacherNumber = teacherNumber;
        this.courseNumber = courseNumber;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TeacherCourse setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getTeacherNumber() {
        return this.teacherNumber;
    }

    @Override
    public TeacherCourse setTeacherNumber(String teacherNumber) {
        this.teacherNumber = teacherNumber;
        return this;
    }

    @Override
    public String getCourseNumber() {
        return this.courseNumber;
    }

    @Override
    public TeacherCourse setCourseNumber(String courseNumber) {
        this.courseNumber = courseNumber;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public TeacherCourse setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public TeacherCourse setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TeacherCourse (");

        sb.append(id);
        sb.append(", ").append(teacherNumber);
        sb.append(", ").append(courseNumber);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITeacherCourse from) {
        setId(from.getId());
        setTeacherNumber(from.getTeacherNumber());
        setCourseNumber(from.getCourseNumber());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITeacherCourse> E into(E into) {
        into.from(this);
        return into;
    }
}
