/*
 * This file is generated by jOOQ.
*/
package com.vzard.mycms.database.tables;


import com.vzard.mycms.database.Keys;
import com.vzard.mycms.database.MyCms;
import com.vzard.mycms.database.tables.records.TeacherCourseRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherCourse extends TableImpl<TeacherCourseRecord> {

    private static final long serialVersionUID = -737329370;

    /**
     * The reference instance of <code>my-cms.teacher_course</code>
     */
    public static final TeacherCourse TEACHER_COURSE = new TeacherCourse();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeacherCourseRecord> getRecordType() {
        return TeacherCourseRecord.class;
    }

    /**
     * The column <code>my-cms.teacher_course.id</code>. id
     */
    public final TableField<TeacherCourseRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "id");

    /**
     * The column <code>my-cms.teacher_course.teacher_num</code>. 教师工号
     */
    public final TableField<TeacherCourseRecord, String> TEACHER_NUM = createField("teacher_num", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "教师工号");

    /**
     * The column <code>my-cms.teacher_course.course_num</code>. 课程号
     */
    public final TableField<TeacherCourseRecord, String> COURSE_NUM = createField("course_num", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "课程号");

    /**
     * The column <code>my-cms.teacher_course.created_at</code>. 创建时间
     */
    public final TableField<TeacherCourseRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "创建时间");

    /**
     * The column <code>my-cms.teacher_course.updated_at</code>. 更新时间
     */
    public final TableField<TeacherCourseRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "更新时间");

    /**
     * Create a <code>my-cms.teacher_course</code> table reference
     */
    public TeacherCourse() {
        this("teacher_course", null);
    }

    /**
     * Create an aliased <code>my-cms.teacher_course</code> table reference
     */
    public TeacherCourse(String alias) {
        this(alias, TEACHER_COURSE);
    }

    private TeacherCourse(String alias, Table<TeacherCourseRecord> aliased) {
        this(alias, aliased, null);
    }

    private TeacherCourse(String alias, Table<TeacherCourseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MyCms.MY_CMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TeacherCourseRecord, Long> getIdentity() {
        return Keys.IDENTITY_TEACHER_COURSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TeacherCourseRecord> getPrimaryKey() {
        return Keys.KEY_TEACHER_COURSE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TeacherCourseRecord>> getKeys() {
        return Arrays.<UniqueKey<TeacherCourseRecord>>asList(Keys.KEY_TEACHER_COURSE_PRIMARY, Keys.KEY_TEACHER_COURSE_TEACHER_COURSE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeacherCourse as(String alias) {
        return new TeacherCourse(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TeacherCourse rename(String name) {
        return new TeacherCourse(name, null);
    }
}
