/*
 * This file is generated by jOOQ.
*/
package com.vzard.mycms.database.tables;


import com.vzard.mycms.database.Keys;
import com.vzard.mycms.database.MyCms;
import com.vzard.mycms.database.tables.records.TeacherRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Teacher extends TableImpl<TeacherRecord> {

    private static final long serialVersionUID = 1054645819;

    /**
     * The reference instance of <code>my-cms.teacher</code>
     */
    public static final Teacher TEACHER = new Teacher();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeacherRecord> getRecordType() {
        return TeacherRecord.class;
    }

    /**
     * The column <code>my-cms.teacher.id</code>. id
     */
    public final TableField<TeacherRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "id");

    /**
     * The column <code>my-cms.teacher.number</code>. 工号
     */
    public final TableField<TeacherRecord, String> NUMBER = createField("number", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "工号");

    /**
     * The column <code>my-cms.teacher.name</code>. 姓名
     */
    public final TableField<TeacherRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "姓名");

    /**
     * The column <code>my-cms.teacher.password</code>. 密码
     */
    public final TableField<TeacherRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "密码");

    /**
     * The column <code>my-cms.teacher.gender</code>. 性别
     */
    public final TableField<TeacherRecord, String> GENDER = createField("gender", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "性别");

    /**
     * The column <code>my-cms.teacher.office</code>. 办公室
     */
    public final TableField<TeacherRecord, String> OFFICE = createField("office", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "办公室");

    /**
     * The column <code>my-cms.teacher.academy</code>. 所在学院
     */
    public final TableField<TeacherRecord, String> ACADEMY = createField("academy", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "所在学院");

    /**
     * The column <code>my-cms.teacher.created_at</code>. 创建时间
     */
    public final TableField<TeacherRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "创建时间");

    /**
     * The column <code>my-cms.teacher.update_at</code>. 更新时间
     */
    public final TableField<TeacherRecord, Timestamp> UPDATE_AT = createField("update_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "更新时间");

    /**
     * Create a <code>my-cms.teacher</code> table reference
     */
    public Teacher() {
        this("teacher", null);
    }

    /**
     * Create an aliased <code>my-cms.teacher</code> table reference
     */
    public Teacher(String alias) {
        this(alias, TEACHER);
    }

    private Teacher(String alias, Table<TeacherRecord> aliased) {
        this(alias, aliased, null);
    }

    private Teacher(String alias, Table<TeacherRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MyCms.MY_CMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TeacherRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TEACHER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TeacherRecord> getPrimaryKey() {
        return Keys.KEY_TEACHER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TeacherRecord>> getKeys() {
        return Arrays.<UniqueKey<TeacherRecord>>asList(Keys.KEY_TEACHER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Teacher as(String alias) {
        return new Teacher(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Teacher rename(String name) {
        return new Teacher(name, null);
    }
}
